##################################################################################################################################################################
## This file contains global replacements variable that can be reused across the configuration files                                                             #
## Every value should be reviewed and properly customized as part of your initial installation                                                                   #
## Refer to the documentation for available options:                                                                                                             #
## https://docs.aws.amazon.com/solutions/latest/landing-zone-accelerator-on-aws/working-with-solution-specific-variables.html#parameter-store-reference-variable #
## https://awslabs.github.io/landing-zone-accelerator-on-aws/latest/typedocs/latest/classes/_aws_accelerator_config.ParameterReplacementConfigV2.html            #
##################################################################################################################################################################

globalReplacements:
  # Accelerator Prefix
  - key: AcceleratorPrefix
    type: String
    value: AWSAccelerator
  # Home Region
  - key: HomeRegion
    type: String
    value: us-east-1 # <----- UPDATE TO YOUR HOME REGION
  - key: EnabledRegions
    type: StringList
    value:
      - "us-east-1" # <----- UPDATE TO INCLUDE HOME REGION + ADDITIONAL REGIONS TO ENABLE
      # - "us-west-2" # <----- ADD ADDITIONAL REGIONS AS NEEDED

  # AWS Budgets Notification Emails
  - key: BudgetsEmail
    type: String
    value: <budget-notifications>@example.com  <----- UPDATE EMAIL ADDRESS

  # SNS email notification configuration
  - key: SecurityHigh
    type: String
    value: <notify-high>@example.com <----- UPDATE EMAIL ADDRESS
  - key: SecurityMedium
    type: String
    value: <notify-medium>@example.com <----- UPDATE EMAIL ADDRESS
  - key: SecurityLow
    type: String
    value: <notify-low>@example.com <----- UPDATE EMAIL ADDRESS

  # Networking
  - key: TransitGatewayASN
    type: Number
    value: 64512 # <---- Update to your specific ASN

  ##  IPAM CONFIGURATION

  # ---- RFC 1918 Range ----
  #
  # 10.0.0.0 - 10.255.255.255 (10/8 prefix)
  # 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
  # 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)
  # Note: Replace the VPC and subnet CIDR ranges based on specific requirements.

  # ---- Overall Design ----
  #   -- Utilize 10.0.0.0/8 to reduce the entry requirement for network infrastructure
  #
  #  Global Pool
  #     - 10.0.0.0/8
  #         - Total IP addresses: 2^24 = 16,777,216 IP addresses
  #         - IP Range: 10.0.0.0 to 10.255.255.255
  #
  #  Regional Pool
  #     - 10.0.0.0/12
  #             - Total IP addresses: 2^20 = 1,048,576 addresses
  #             - IP Range: 10.0.0.0 to 10.15.255.255
  #          - 10.0.0.0/14 - Core VPCs
  #               - 10.0.0.0/20 - Ingress VPC
  #               - 10.0.16.0/24 - Egress VPC
  #               - 10.0.17.0/24 - Inspection VPC
  #               - 10.0.18.0/24 - Available
  #               - 10.0.19.0/24 - Available
  #               - 10.0.20.0/22 - Endpoints VPC
  #               - 10.0.24.0/21 - SharedServices VPC
  #               - 10.0.32.0/19 - Available
  #               - 10.0.64.0/18 - Available
  #               - 10.0.128.0/17 - Available
  #               - 10.1.0.0/16 - Available
  #               - 10.2.0.0/15 - SandBox VPCs
  #           - 10.4.0.0/14 - Dev Workload VPCs
  #           - 10.8.0.0/14 - Test Workload VPCs
  #           - 10.12.0.0/14 - Prod Workload VPCs

  #########################
  # IPAM Pool Definitions #
  #########################
  ## Global Pool
  - key: GlobalCidr
    type: String
    value: "10.0.0.0/8"
  ## Regional Pool
  - key: HomeRegionRegionalCidr
    type: String
    value: "10.0.0.0/12"
  ## Dev VPCs Pool
  - key: HomeRegionDevWorkloadsCidr
    type: String
    value: "10.4.0.0/14"
  ## Test VPCs Pool
  - key: HomeRegionTestWorkloadsCidr
    type: String
    value: "10.8.0.0/14"
  ## Prod VPCs Pool
  - key: HomeRegionProdWorkloadsCidr
    type: String
    value: "10.12.0.0/14"

  #############################################
  # HUB & SPOKE VPC DEPLOYMENT MODEL ONLY!!!! #
  #############################################
  ## Dev Workloads VPCs
  - key: HomeRegionDevWorkloadsVpcMaskLength
    type: Number
    value: 22
  - key: HomeRegionDevWorkloadsAppSubnetMaskLength
    type: Number
    value: 24
  - key: HomeRegionDevWorkloadsDataSubnetMaskLength
    type: Number
    value: 26

  ## Test Workloads VPCs
  - key: HomeRegionTestWorkloadsVpcMaskLength
    type: Number
    value: 22
  - key: HomeRegionTestWorkloadsAppSubnetMaskLength
    type: Number
    value: 24
  - key: HomeRegionTestWorkloadsDataSubnetMaskLength
    type: Number
    value: 26

  ## Prod Workloads VPCs
  - key: HomeRegionProdWorkloadsVpcMaskLength
    type: Number
    value: 22
  - key: HomeRegionProdWorkloadsAppSubnetMaskLength
    type: Number
    value: 24
  - key: HomeRegionProdWorkloadsDataSubnetMaskLength
    type: Number
    value: 26

  ########################################
  # SHARED VPC DEPLOYMENT MODEL ONLY!!!! #
  ########################################
  ## SharedVpcCidrAssignments
  - key: HomeRegionSharedDevVpcMaskLength
    type: Number
    value: 16
  - key: HomeRegionSharedTestVpcMaskLength
    type: Number
    value: 16
  - key: HomeRegionSharedProdVpcMaskLength
    type: Number
    value: 16

  #############################################
  # Used by BOTH Networking Deployment Models #
  #############################################
  ## Ingress VPC
  - key: HomeRegionIngressCidr
    type: String
    value: "10.0.0.0/20"
  - key: HomeRegionIngressVpcMaskLength
    type: Number
    value: 20
  - key: HomeRegionIngressFwSubnetMaskLength
    type: Number
    value: 27
  - key: HomeRegionIngressPublicSubnetMaskLength
    type: Number
    value: 22
  ## Egress VPC
  - key: HomeRegionEgressCidr
    type: String
    value: "10.0.16.0/24"
  - key: HomeRegionEgressVpcMaskLength
    type: Number
    value: 24
  - key: HomeRegionEgressFwSubnetMaskLength
    type: Number
    value: 27
  - key: HomeRegionEgressPublicSubnetMaskLength
    type: Number
    value: 28
  ## SharedServices VPC
  - key: HomeRegionSharedServicesCidr
    type: String
    value: "10.0.24.0/21"
  - key: HomeRegionSharedServicesVpcMaskLength
    type: Number
    value: 21
  ## Inspection VPC
  - key: HomeRegionInspectionCidr
    type: String
    value: "10.0.17.0/24"
  - key: HomeRegionInspectionVpcMaskLength
    type: Number
    value: 24
  - key: HomeRegionInspectionFwSubnetMaskLength
    type: Number
    value: 28
  ## Endpoints VPC
  - key: HomeRegionEndpointsCidr
    type: String
    value: "10.0.20.0/22"
  - key: HomeRegionIngressEndpointsVpcMaskLength
    type: Number
    value: 22
  - key: HomeRegionIngressEndpointsSubnetMaskLength
    type: Number
    value: 24
  ## SharedServices
  - key: HomeRegionSharedServicesWebSubnetMaskLength
    type: Number
    value: 25
  - key: HomeRegionSharedServicesAppSubnetMaskLength
    type: Number
    value: 24
  - key: HomeRegionSharedServicesDataSubnetMaskLength
    type: Number
    value: 26
